console.log("hey my name is saeed")
// var d = 5;
// var b = 10;
//  var c = "harry"; not use

let a = 12;
let b = 10;
let c = "harry";

console.log(a + b)
// console.log(a + b + c)  another exapmle
console.log(typeof a, typeof b, typeof c)

{
    let a = 66;
    console.log(a);
} // a group

console.log(a);

// const a1 = 5;


// new example
let x = "harry";
let y = 22;
let z = 4.2;
const p = true;
let q = undefined;
let r = null;
console.log(x, y, z, p, q, r);
console.log(typeof x, typeof y, typeof z, typeof p, typeof q, typeof r);


// new example
let o = {
    name: "harry",
    "jop code": 5600,
    "is not good " :false,
}
o.selory= "2000coroes "
console.log(o) 
o.selory= "3000coroes "
console.log(o)
